/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.system;

/**
 *
 * @author 44789
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jAccountBalanceButtonLabel = new javax.swing.JLabel();
        jBillPaymentButtonLabel = new javax.swing.JLabel();
        jInstantPaymentButtonLabel = new javax.swing.JLabel();
        jOrderChequeBookButtonLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("DASHBOARD");

        jAccountBalanceButtonLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jAccountBalanceButtonLabel.setText("Account Balance");
        jAccountBalanceButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAccountBalanceButtonLabelMouseClicked(evt);
            }
        });

        jBillPaymentButtonLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBillPaymentButtonLabel.setText("Bill Payment");
        jBillPaymentButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBillPaymentButtonLabelMouseClicked(evt);
            }
        });

        jInstantPaymentButtonLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jInstantPaymentButtonLabel.setText("Instant Payment Transfer");
        jInstantPaymentButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInstantPaymentButtonLabelMouseClicked(evt);
            }
        });

        jOrderChequeBookButtonLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jOrderChequeBookButtonLabel.setText("Order Cheque Book");
        jOrderChequeBookButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOrderChequeBookButtonLabelMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("LOGOUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jBillPaymentButtonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jOrderChequeBookButtonLabel)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jAccountBalanceButtonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jInstantPaymentButtonLabel)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAccountBalanceButtonLabel)
                    .addComponent(jInstantPaymentButtonLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBillPaymentButtonLabel)
                    .addComponent(jOrderChequeBookButtonLabel))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAccountBalanceButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAccountBalanceButtonLabelMouseClicked
        // TODO add your handling code here:
        accountBalance obj = new accountBalance();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jAccountBalanceButtonLabelMouseClicked

    private void jInstantPaymentButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInstantPaymentButtonLabelMouseClicked
        // TODO add your handling code here:
        instantPayment obj = new instantPayment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jInstantPaymentButtonLabelMouseClicked

    private void jBillPaymentButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBillPaymentButtonLabelMouseClicked
        // TODO add your handling code here:
        billPayment obj = new billPayment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBillPaymentButtonLabelMouseClicked

    private void jOrderChequeBookButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOrderChequeBookButtonLabelMouseClicked
        // TODO add your handling code here:
        orderCheque obj = new orderCheque();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jOrderChequeBookButtonLabelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         loginPage obj = new loginPage();
                 obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAccountBalanceButtonLabel;
    private javax.swing.JLabel jBillPaymentButtonLabel;
    private javax.swing.JLabel jInstantPaymentButtonLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jOrderChequeBookButtonLabel;
    // End of variables declaration//GEN-END:variables
}
